### ISSUE TITLE
Compiler errors on OSX 10.10/ OF 0.8.4 release

### ISSUE THREAD

**Issue by indefinit** [vanderlin/ofxBox2d#90]
Hello,

I'm trying to help a student with her Box2D code but seem to be getting a bunch of compile errors when running either the examples or a new test app with OSX 10.10 and OF v 0.8.4 release.  I initially thought the errors had something to do with compiler language Dialect ("use of undeclared static_assert") but I now think it might have more to do with my version of OF.  Do I need to pull a specific 084 tag, or is there a preferred OSX setup for using this addon?  Thanks in advance!

**Comment by indefinit** [comment]
After tweaking the deployment target settings to OSX 10.8 it solved a lot of the errors, but I am now getting <tr1/unordered_map> file not found.

**Comment by ikbenmacje** [comment]
I am having the same issues: /of_v0.8.4_osx_release/addons/ofxBox2d/libs/Box2D/Common/b2Math.h:30:2: Use of undeclared identifier 'static_assert'; did you mean 'static_cast'?

Using OSX 10.9.5 with Xcode 6.2 and OF v 0.8.4 Release. Also setting the deployment target does not help solve the error.

**Comment by kylemcdonald** [comment]
please grab the ofxBox2d repo again and try again.

the project files that come with the repo are working for me under 0.8.4 and 10.10.

there were some bugs with ofDrawLine/ofDrawCircle which are new to 0.9.0 accidentally being included in master, but now the 0.9.0 version is in develop.

**Comment by ikbenmacje** [comment]
I grabbed a new version from the ofxBox2d and tried to build the example-Simple I get one error:

"of_v0.8.4_osx_release/addons/ofxBox2d/src/ofxBox2dJoint.cpp:113:2: Use of undeclared identifier 'ofDrawLine'; did you mean 'ofDrawCone'?"

This actually seems to point to the bugs you mentioned with ofDrawLine/ofDrawCirlce. Kyle because of your comment I am slightly confused.. which repo is the last stable version of box2d yours? or  vanderlin?

**Comment by kylemcdonald** [comment]
sorry, i thought i had pushed to this repo, but i pushed to my own.

please use this repo. i just checked and there should not be any instance of ofDrawLine in master.
